name: New Rule Pipeline
run-name: New Rule Pipeline 🚀
on:
  workflow_dispatch:
    inputs:
      rule_name:
        type: text
        description: "Rule Name:"
        required: true
      domain:
        type: text
        description: "Domain:"
        required: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - run: echo ${{ github.actor }}
      - run:
          git config --global user.name "StarkeEnrico"
          
          echo 'Add ressource new CNAME ${{ github.event.inputs.rule_name }}' >> x

          git commit -am "Change x" 
 
          git push origin master
